export const API_BASE_URL = "http://www.mocky.io/v2"



export const fieldTypes = {
  FETCH_COORDINATOR: "FETCH_COORDINATOR",
  FETCH_COORDINATOR_SUCCESS: "FETCH_COORDINATOR_SUCCESS",
  FETCH_RESPONSIBLE: "FETCH_RESPONSIBLE",
  FETCH_RESPONSIBLE_SUCCESS: "FETCH_RESPONSIBLE_SUCCESS"
}
